routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/', 'ProductController@index')->name('product.index');
Route::resource('/categories', 'CategoryController');
Route::get('/products/edit/{product}', 'ProductController@edit')->name('product.edit');
Route::get('/products', 'ProductController@create')->name('product.create');
Route::post('/products', 'ProductController@store')->name('product.store');
Route::put('/products/update/{product}', 'ProductController@update')->name('product.update');
Route::delete('/products/delete/{product}', 'ProductController@destroy')->name('product.destroy');
Route::get('/search', 'ProductController@search')->name('product.search');
Route::get('/products/filter', 'ProductController@filter')->name('product.filter');
Route::get('/products/{product}', 'ProductController@show')->name('product.show');
Route::resource('/comments', 'CommentController');
Route::resource('/likes', 'LikeController');
Route::post('/replies/{replies}', 'LikeController@replyLikes');
Route::resource('/replies', 'ReplyController');
//Admin part
Route::get('/admin', 'AdminController@admin')->middleware('admin')->name('admin');
Route::get('/notadmin', 'AdminController@not_admin');

resources/views/admin.blade.php
<h1>Hello Admin</h1>

resources/views/category.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <form method="POST" action="{{ route('categories.store') }}" class="col-md-5 mx-auto mt-5" id="category_form">
            @csrf
            <div class="form-group row">
                <label for="name" class="col-md-3 col-form-label text-md-right">{{ __('Name') }}</label>
                <div class="col-md-6">
                    <input id="name" type="text" class="form-control" name="name"  autofocus>
                        <span role="alert">
                    <strong class="errors"></strong>
                        </span>
                </div>
            </div>
            <div class="form-group row mb-0">
                <div class="col-md-6 offset-md-3">
                    <button type="button" class="btn btn-primary js_category_save">
                        {{ __('Save') }}
                    </button>
                </div>
            </div>
        </form>
        <div class="col-md-4">
            <table class="table table-sm" id="category_list">
                <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Name</th>
                    <th scope="col">Created at</th>
                    <th scope="col">Edit</th>
                    <th scope="col">Delete</th>
                </tr>
                </thead>
                <tbody>
                @foreach($categories as $category)
                    <tr data-id="{{$category->id}}">
                        <td data-id='category_id' scope="row" data-target='id'>{{$category->id}}</td>
                        <td data-target='name'>{{$category->name}}</td>
                        <td data-created="created_at" data-target='created_at'>{{$category->created_at}}</td>
                        <td>
                            <button data-id="{{$category->id}}" type="button" class="btn btn-secondary js_edit_category">
                                Edit
                            </button>
                        </td>
                        <td>
                            <button data-id="{{$category->id}}" type="submit" class="btn btn-secondary js_delete_category">
                                Delete
                            </button>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>

    <!-- Modal -->

    <div class="modal fade" id="category_edit_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Make changes</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="js_updated_data">
                        @csrf
                        <input type="hidden" name="id" value="">
                        <div class="form-group row">
                            <label for="category_name" class="col-sm-2 col-form-label">Name</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="name" id="category_name">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="category_type" class="col-sm-2 col-form-label">Updated_at</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="created_at" id="category_type">
                            </div>
                        </div>
                    </form>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary js_update_category">Update</button>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/comments.blade.php
<li>
    <div class="comment-main-level">
        <!-- Avatar -->
        <div class="comment-avatar"><img
                    src="https://vignette.wikia.nocookie.net/csydes-test/images/6/6b/%28AnimeFreak%29_Mirai_Kuriyama.png/revision/latest?cb=20170404065736"
                    alt=""></div>
        <!-- Contenedor del Comentario -->
        <div class="comment-box">
            <div class="comment-head">
                <h6 class="comment-name by-author"><a href="http://creaticode.com/blog">{{$comment->user->name}}</a></h6>
                <button class="delete" data-id="{{$comment->id}}">
                    <i class="fa fa-heart"></i>
                </button>
                <button class="like" data-id="{{$comment->id}}">
                    <i class="fa fa-reply"></i>
                </button>
                <button class="delete" data-id="{{$comment->id}}">
                    <i class="fa fa-trash"> </i>
                </button>
                <span>{{$time}}</span>
            </div>
            <div class="comment-content">
                {{$comment->body}}
            </div>
            <div class="reply-box"></div>
            <ul class="comments-list reply-list"></ul>
        </div>

    </div>
</li>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Dashboard</div>
                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        <table class="table product_list" id="result_table">
                            <thead class="thead-dark">
                            <tr>
                                <th scope="col">category</th>
                                <th scope="col">name</th>
                                <th scope="col">image</th>
                                <th scope="col">price</th>
                                <th scope="col">created at</th>
                                @if(Auth::check())
                                <th scope="col">edit</th>
                                <th scope="col">delete</th>
                                @endif
                                <th scope="col">view</th>
                            </tr>
                            </thead>
                            @foreach($products as $product)
                                <tr data-id="{{$product->id}}">
                                    <td>{{$product->category->name}}</td>
                                    <td data-target="name">{{$product->name}}</td>
                                    <td data-target="image_file">
                                        @if(count($product->files) != 0)
                                            <a id="resize"><img src="{{asset($product->files[0]->name)}}" alt=""
                                                                style="height: 70px; width: 70px" class="product_image">
                                            </a>
                                        @else
                                            <a id="resize"> <img
                                                        src="https://cdn3.iconfinder.com/data/icons/faticons/32/picture-01-512.png"
                                                        alt="" style="height: 70px; width: 70px" class="product_image">
                                            </a>
                                        @endif
                                    </td>
                                    <td data-target="price">{{$product->price}}</td>
                                    <td data-target="created_at">{{$product->created_at}}</td>
                                    @if(Auth::check())
                                    <td>
                                        <button data-id="{{$product->id}}" type="button"
                                                class="btn btn-secondary js_edit_product">Edit
                                        </button>
                                    </td>
                                    <td>
                                        <button data-id="{{$product->id}}" type="button"
                                                class="btn btn-secondary js_delete_product">Delete
                                        </button>
                                    </td>
                                    @endif
                                    <td>

                                        {{--my option-- ^-^}}

                                        {{--<button data-id="{{$product->id}}" type="button"--}}
                                                {{--class="btn btn-secondary js_view_product" onclick="window.location=`{{ url("/products/{$product->id}/show")}}`"> View product--}}
                                        {{--</button>--}}

                                        {{--Mihran's option :P--}}
                                        <a href="{{route('product.show', ['product' => $product->id])}}" class="btn btn-secondary js_view_product" class="">View product</a>
                                    </td>
                                </tr>
                            @endforeach

                        </table>


                        {{$products->links()}}
                    </div>
                </div>
            </div>
            <div class="col-md-4">

                {{--live search results component--}}

                <div class="col-md-12" id="search_result">

                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="product_edit_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Make changes</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="js_updated_data">
                        @csrf
                        <input type="hidden" name="id" value="">
                        <div class="form-group row">
                            <label for="name" class="col-sm-2 col-form-label">Name</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="product_name" id="product_name">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="type" class="col-sm-2 col-form-label">updated_at</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="updated_at" id="product_type">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="price" class="col-sm-2 col-form-label">Price</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="product_price" id="price">
                            </div>
                        </div>
                    </form>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary js_update_product">Update</button>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="imagePreviewModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-body mbody">
                    <img src="" alt="" id="preview_img" width="700">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/notadmin.blade.php
<h1>You're not admin, Exit please</h1>

resources/views/product.blade.php
@extends('layouts.app')

@section('content')
    <form method="POST" action="{{ route('product.store') }}" class="col-md-5 mx-auto mt-5" id="product_form" enctype="multipart/form-data">
        @csrf
        <div class="form-group row">
            <label for="name" class="col-md-3 col-form-label text-md-right">{{ __('Name') }}</label>
            <div class="col-md-6">
                <input id="name" type="text" class="form-control" name="name"   autofocus>

                    <span role="alert">
                        <strong class="errors_name"></strong>
                    </span>
            </div>
        </div>

        <div class="form-group row">
            <label for="price" class="col-md-3 col-form-label text-md-right">{{ __('Price') }}</label>
            <div class="col-md-6">
                <input id="price" type="number" class="form-control"
                       name="price">

                <span role="alert">
                        <strong class="errors_price"></strong>
                    </span>
            </div>
        </div>

        {{-- save the results--}}

        <div class="form-group row">
            <label for="category" class="col-md-3 col-form-label text-md-right">{{ __('Category') }}</label>
            <div class="col-md-6">
                <select name="category" id="category" class="form-control">
                    @foreach($categories as $category)
                        <option value="{{$category->id}}"> {{$category->name}} </option>
                    @endforeach
                </select>
            </div>
        </div>
        <div class="form-group row">
            <label for="upload" class="col-md-3 col-form-label text-md-right">{{ __('Upload') }}</label>
            <div class="col-md-6">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroupFileAddon01">Upload</span>
                    </div>
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="inputGroupFile01" aria-describedby="inputGroupFileAddon01" name="files">
                        <span></span>
                        <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
                        <span></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group row mb-0">
            <div class="col-md-6 offset-md-3">
                <button type="submit" class="btn btn-primary js_product_save">
                    {{ __('Save') }}
                </button>
            </div>
        </div>
    </form>
@endsection

resources/views/product_row.blade.php
{{--@php--}}

        {{--dd($product->id)--}}
        {{--@endphp--}}
<tr data-id="{{$product->id}}">
    <td>{{$product->category->name}}</td>
    <td data-target="name">
        @if(count($product->files) != 0)
            <img src="{{asset($product->files[0]->name)}}" alt=""
                 style="height: 70px; width: 70px">
        @else
            <img src="https://cdn3.iconfinder.com/data/icons/faticons/32/picture-01-512.png"
                 alt="" style="height: 70px; width: 70px">
        @endif
        {{$product->name}}
    </td>
    <td data-target="price">{{$product->price}}</td>
    <td data-target="created_at">{{$product->created_at}}</td>
    <td>
        <button data-id="{{$product->id}}" type="button"
                class="btn btn-secondary js_edit_product">Edit
        </button>
    </td>
    <td>
        <button data-id="{{$product->id}}" type="button"
                class="btn btn-secondary js_delete_product">Delete
        </button>
    </td>
</tr>

resources/views/range-results.blade.php
{{--Component to be rendered  when range works--}}

<table class="table product_list" id="result_table">
    <thead class="thead-dark">
    <tr>
        <th scope="col">name</th>
        <th scope="col">price</th>
        <th scope="col">created at</th>
        <th scope="col">edit</th>
        <th scope="col">delete</th>
    </tr>
    </thead>

    @foreach($results as $result)
        <tr data-id="{{$result->id}}">
            <td data-target="name">
                @if(count($result->files) != 0)
                    <img src="{{asset($result->files[0]->name)}}" alt=""
                         style="height: 70px; width: 70px">
                @else
                    <img src="https://cdn3.iconfinder.com/data/icons/faticons/32/picture-01-512.png"
                         alt="" style="height: 70px; width: 70px">
                @endif
            </td>
            <td data-target="price">{{$result->price}}</td>
            <td data-target="created_at">{{$result->created_at}}</td>
            <td>
                <button data-id="{{$result->id}}" type="button"
                        class="btn btn-secondary js_edit_product">Edit
                </button>
            </td>
            <td>
                <button data-id="{{$result->id}}" type="button"
                        class="btn btn-secondary js_delete_product">Delete
                </button>
            </td>
        </tr>
    @endforeach
</table>

resources/views/reply.blade.php
{{--reply level of comment--}}
<div class="comment-avatar"><img
            src="https://img.purch.com/w/660/aHR0cDovL3d3dy5saXZlc2NpZW5jZS5jb20vaW1hZ2VzL2kvMDAwLzAwNy80MjEvb3JpZ2luYWwvMDUwNzExX2dlbmVyaWNfY293XzAyLmpwZw=="
            alt=""></div>
    <div class="comment-box">
        <div class="comment-head">
            <h6 class="comment-name"><a href="http://creaticode.com/blog"></a></h6>
            <button class="reply-like" data-id="{{$reply->id}}">
                <i class="fa fa-heart"></i>
            </button>
            <button class="reply-of-reply" data-id="{{$reply->id}}">
                <i class="fa fa-reply"></i>
            </button>
            <button class="reply-delete" data-id="{{$reply->id}}">
                <i class="fa fa-trash"> </i>
            </button>
        </div>
        <div class="comment-content">
            {{$reply->body}}
        </div>
    </div>

resources/views/search.blade.php
<div>
    @foreach($results as $result)
        <div class="card-group">
            <div class="card">
                <img class="card-img-top" src="{{asset($result->files[0]->name)}}" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">{{$result->name}}</h5>
                    <p class="card-text">Price : {{$result->price}} $</p>
                    <p class="card-text">
                        <small class="text-muted"></small>
                    </p>
                </div>
            </div>
        </div> <br>
    @endforeach
</div>

resources/views/singlePage.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-6 justify-content-center">
                <div class="card text-center">
                    <img class="card-img-top" src="{{$product->files->first() ? $product->files->first()->name : ''}}" alt="Card image cap">
                    <div class="card-header">
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{$product->name}}</h5>
                        <p class="card-text">{{$product->price}}</p>
                    </div>
                </div>
                @if(Auth::check())
                    <form action="{{route('comments.store')}}" method="post" id="comment_form">
                        @csrf
                        <input type="hidden" name="product" value="{{$product->id}}">
                        <label for="comment"></label>
                        <textarea name="comment" id="comment" class="form-control"
                                  placeholder="your comment here..."> </textarea>
                        <br>
                        <button class="btn btn-primary" type="button" id="save_comment">Add comment</button>
                    </form>
                @endif
            </div>
            <div class="col-md-2" id="comments_section">
                <div class="comments-container">
                    <ul id="comments-list" class="comments-list">
                        @if(isset($product))
                            @foreach($product->comments as $comment)
                                <li class="comment-list">
                                    <div class="comment-main-level">
                                        <!-- Avatar -->
                                        <div class="comment-avatar"><img
                                                    src="https://vignette.wikia.nocookie.net/csydes-test/images/6/6b/%28AnimeFreak%29_Mirai_Kuriyama.png/revision/latest?cb=20170404065736"
                                                    alt=""></div>
                                        <!-- Contenedor del Comentario -->
                                        <div class="comment-box">
                                            <div class="comment-head">
                                                <h6 class="comment-name by-author">
                                                    <a>{{$comment->user->name}}</a>
                                                </h6>
                                                @if(Auth::check())
                                                    <button class="like"
                                                            value="{{$comment->commentable->id}}"
                                                            data-id="{{$comment->id}}">
                                                        <i style="color: {{count($comment->likes) ? 'red' : 'grey'}}"
                                                           class="fa fa-heart like_icon"></i>
                                                    </button>
                                                    <button class="open-reply-form" data-id="{{$comment->id}}">
                                                        <i class="fa fa-reply"> </i>
                                                    </button>
                                                    <button class="delete" data-id="{{$comment->id}}">
                                                        <i class="fa fa-trash"> </i>
                                                    </button>
                                                    <span>{{$comment->created_at->diffForHumans()}}</span>
                                                @endif
                                            </div>
                                            <div class="comment-content">
                                                {{$comment->body}}
                                            </div>
                                            <div class="reply-box"></div>
                                            <ul class="comments-list reply-list">
                                                @foreach($comment->replies as $reply)
                                                    <li class="reply-list">
                                                        <div class="comment-avatar"><img
                                                                    src="https://img.purch.com/w/660/aHR0cDovL3d3dy5saXZlc2NpZW5jZS5jb20vaW1hZ2VzL2kvMDAwLzAwNy80MjEvb3JpZ2luYWwvMDUwNzExX2dlbmVyaWNfY293XzAyLmpwZw=="
                                                                    alt=""></div>
                                                        <div class="comment-box">
                                                            <div class="comment-head">
                                                                <h6 class="comment-name"><a
                                                                            href="http://creaticode.com/blog"></a></h6>
                                                                @if(Auth::check())
                                                                    <button class="reply-like" data-id="{{$reply->id}}">
                                                                        <i class="fa fa-heart"></i>
                                                                    </button>
                                                                    <button class="reply-delete"
                                                                            data-id="{{$reply->id}}">
                                                                        <i class="fa fa-trash"> </i>
                                                                    </button>
                                                                    <span> {{$reply->created_at->diffForHumans()}}</span>
                                                                @endif
                                                            </div>
                                                            <div class="comment-content">
                                                                {{$reply->body}}
                                                            </div>
                                                        </div>
                                                    </li>
                                                @endforeach

                                            </ul>
                                        </div>
                                    </div>
                                </li>
                            @endforeach
                        @endif
                    </ul>
                </div>
            </div>
        </div>
    </div>
@endsection